Repository ultralytics/yolo-flutter-app, pull requests merged in 2024-10, with the labels that each got.

#66 Ultralytics Code Refactor https://ultralytics.com/actions
  .github/workflows/cla.yml
  .github/workflows/format.yml
  README.md
Labels: documentation, enhancement

#59 Change to a meaningfull logo to switch cameras
  example/lib/main.dart
Labels: enhancement

#68 Fix incorrect argument check in MethodCallHandler.swift
  ios/Classes/MethodCallHandler.swift
Labels: bug, enhancement

#64 Storage permissions compatibility on Android 13+ devices
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  android/src/main/AndroidManifest.xml
  example/android/app/build.gradle
  example/android/app/src/main/AndroidManifest.xml
  example/android/build.gradle
  example/android/gradle/wrapper/gradle-wrapper.properties
  example/android/settings.gradle
  example/lib/main.dart
  example/pubspec.lock
  example/pubspec.yaml
Labels: bug, dependencies, enhancement
