Repository ultralytics/yolo-flutter-app, pull requests merged in 2025-06, with the labels that each got.

#198 feat: add changelog
  CHANGELOG.md
  pubspec.yaml
Labels: documentation, enhancement

#202 Fix non-sequential version publishing
  CHANGELOG.md
  pubspec.yaml
Labels: enhancement, devops

#206 Rename docs/ dir to doc/
  README.md
  doc/api.md
  doc/index.md
  doc/install.md
  doc/models.md
  doc/performance.md
  doc/quickstart.md
  doc/troubleshooting.md
  doc/usage.md
Labels: documentation

#205 Add Dart dry run publish to CI
  .github/workflows/ci.yml
  CHANGELOG.md
  pubspec.yaml
Labels: enhancement, devops

#208 Add issue tracker field to pubspec.yml
  pubspec.yaml
Labels: documentation, enhancement

#211 Fix `withOpacity()` deprecation infos
  .github/workflows/analyzer.yml
  example/lib/presentation/screens/camera_inference_screen.dart
Labels: enhancement, devops

#215 Cleanup example directory
  CHANGELOG.md
  example/README_MULTI_INSTANCE_TEST.md
  example/assets/.gitkeep
  example/main.dart
  example/pubspec.yaml
  example/test/README.md
  example/test/plugin_integration_test.dart
  pubspec.yaml
Labels: dependencies, documentation, enhancement

#217 Potential fix for code scanning alert no. 1: Workflow does not contain permissions
  .github/workflows/stale.yml
Labels: enhancement, devops

#256 Fix: Resolve OBB Streaming Data Export Failure
  android/src/main/kotlin/com/ultralytics/yolo/YOLOView.kt
Labels: enhancement, detect, OBB
