Repository ultralytics/yolo-flutter-app, pull requests merged in 2025-01, with the labels that each got.

#85 Update format.yml
  .github/workflows/format.yml
Labels: enhancement, devops

#87 Standardize license headers in TOML/YAML files
  .github/workflows/cla.yml
  .github/workflows/format.yml
  .github/workflows/stale.yml
  .github/workflows/tag.yml
  analysis_options.yaml
  example/analysis_options.yaml
  example/assets/metadata-cls.yaml
  example/assets/metadata.yaml
  example/pubspec.yaml
  pubspec.yaml
Labels: documentation, devops

#90 feat: implement switch camera functionality
  .vscode/settings.json
  android/src/main/cpp/opencv-mobile-4.6.0-android/sdk/native/jni/include/opencv2/core/cvdef.h
  android/src/main/cpp/opencv-mobile-4.6.0-android/sdk/native/jni/include/opencv2/core/hal/intrin_avx512.hpp
  android/src/main/java/com/ultralytics/ultralytics_yolo/CameraPreview.java
  android/src/main/java/com/ultralytics/ultralytics_yolo/predict/detect/TfliteDetector.java
  example/ios/Podfile.lock
  example/ios/Runner.xcodeproj/project.pbxproj
  example/ios/Runner/AppDelegate.swift
  example/lib/main.dart
  example/pubspec.lock
  ios/Classes/FLNativeView.swift
  ios/Classes/FLNativeViewFactory.swift
  ios/Classes/LocalModel.swift
  ios/Classes/MethodCallHandler.swift
  ios/Classes/ObjectDetector.swift
  ios/Classes/SwiftUltralyticsYoloPlugin.swift
  ios/Classes/VideoCapture.swift
  lib/camera_preview/ultralytics_yolo_camera_controller.dart
  lib/ultralytics_yolo_platform_channel.dart
Labels: dependencies, enhancement, detect
