Repository ultralytics/yolo-flutter-app, pull requests merged in 2025-05, with the labels that each got.

#113 Ultralytics Actions JSON, CSS and autolabel support
  .github/workflows/format.yml
Labels: enhancement, devops

#117 Add Dart formatting
  .github/workflows/format.yml
  example/lib/main.dart
  example/test/widget_test.dart
  lib/camera_preview/ultralytics_yolo_camera_controller.dart
  lib/camera_preview/ultralytics_yolo_camera_preview.dart
  lib/predict/classify/classification_result_overlay.dart
  lib/predict/detect/object_detector_painter.dart
  lib/ultralytics_yolo_platform_channel.dart
  lib/yolo_model.dart
Labels: enhancement, devops

#119 Add Permissions to Ultralytics Actions `format.yml`
  android/src/main/cpp/opencv-mobile-4.6.0-android/sdk/native/jni/include/opencv2/core/cuda/detail/vec_distance_detail.hpp
  android/src/main/cpp/opencv-mobile-4.6.0-android/sdk/native/jni/include/opencv2/core/cuda/vec_distance.hpp
Labels: enhancement, devops

#120 Add Code Coverage
  .github/workflows/code-coverage.yml
  .gitignore
  android/src/main/res/layout/activity_tflite_camera.xml
  example/android/app/src/main/res/drawable-v21/launch_background.xml
  example/android/app/src/main/res/values-night/styles.xml
  example/android/app/src/main/res/values/styles.xml
  lib/camera_preview/ultralytics_yolo_camera_controller.dart
  lib/predict/detect/object_detector_painter.dart
  pubspec.yaml
  test/assets/metadata.json
  test/predictor_test.dart
  test/ultralytics_yolo_platform_interface_test.dart
  test/yolo_model_test.dart
Labels: dependencies, enhancement, devops

#131 Delete UE4HU2R4C5
  UE4HU2R4C5
Labels: enhancement

#133 Remove OpenCV mentions in ultralytics.h
  android/src/main/cpp/ultralytics.h
Labels: dependencies, enhancement

#134 Cleanup warnings
  .github/workflows/analyzer.yml
  .github/workflows/ci.yml
  analysis_options.yaml
  example/ios/Podfile.lock
  example/lib/main.dart
  example/pubspec.lock
  ios/Classes/UltralyticsYoloPlugin.m
  lib/camera_preview/ultralytics_yolo_camera_controller.dart
  lib/predict/segment/detected_segment.dart
  lib/predict/segment/segment_detector_painter.dart
  lib/ultralytics_yolo_platform_channel.dart
  pubspec.yaml
  test/predict/classify/image_classifier_test.dart
  test/predict/detect/object_detector_test.dart
  test/predict/predictor_test.dart
  test/predict/segment/detected_segment_test.dart
  test/predictor_test.dart
  test/ultralytics_yolo_platform_channel_test.dart
  test/ultralytics_yolo_platform_interface_test.dart
  test/yolo_model_test.dart
Labels: dependencies, enhancement, devops

#137 Update README with TFLite and iOS export code
  README.md
Labels: documentation, enhancement, exports

#145 Update pubspec.yaml
  example/lib/image_picker.dart
  example/lib/main.dart
  lib/camera_preview/ultralytics_yolo_camera_preview.dart
  lib/predict/classify/classification_result_overlay.dart
  lib/predict/detect/object_detector_painter.dart
  lib/predict/segment/segment_detector_painter.dart
  pubspec.yaml
Labels: documentation

#147 Resolve astral uv warnings in publish CI
  .github/workflows/publish.yml
Labels: enhancement, devops

#149 Markdown file improvements
  README.md
  example/README.md
  example/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md
  example/test/README.md
  ios/Classes/README.md
Labels: documentation

#150 Update yolo_result_simple_test.dart + integration tests
  test/yolo_integration_test.dart
  test/yolo_result_simple_test.dart
Labels: enhancement, detect

#151 Create yolo_static_methods_test.dart
  test/yolo_static_methods_test.dart
Labels: enhancement, detect

#152 Create yolo_controller_test.dart
  test/yolo_controller_test.dart
Labels: enhancement, detect

#155 Sort dependencies in pubspec.yaml
  pubspec.yaml
  test/yolo_integration_test.dart
  test/yolo_result_test.dart
Labels: dependencies, enhancement

#179 Fix publish action
  .github/workflows/publish.yml
Labels: enhancement, devops

#180 Fix publish action
  .github/workflows/publish.yml
Labels: enhancement, devops

#183 Fix publish action
  .github/workflows/publish.yml
Labels: enhancement, devops

#186 Create publish.yml
  .github/workflows/create-tag.yml
  .github/workflows/publish-on-tag.yml
  .github/workflows/publish.yml
  CHANGELOG.md
  example/main.dart
  pubspec.yaml
Labels: enhancement, devops

#188 Update publish.yml GitHub token
  .github/workflows/publish-on-tag.yml
  .github/workflows/publish.yml
Labels: enhancement, devops

#190 Update OIDC publish action on main
  .github/workflows/publish-on-tag.yml
Labels: enhancement, devops

#191 Update Publish on tag action
  .github/workflows/publish-on-tag.yml
  .github/workflows/publish.yml
  .github/workflows/tag.yml
  CHANGELOG.md
  pubspec.yaml
Labels: documentation, devops
